EXTRA_LABEL_COLORS = [
    "orange1",
    "DarkOrange",
    "CadetBlue1",
    "DeepSkyBlue",
    "SkyBlue",
    "purple1",
    "MediumPurple1",
    "SpringGreen2",
    "SpringGreen1",
    "SeaGreen1",
    "green1",
    "IndianRed1",
    "PaleVioletRed1",
    "Red1",
    "VioletRed1",
]
VIDEO_BACKGROUND_THEMES = [
    "Sunrise",
    "Forest",
    "Beach",
    "Cityscape",
    "Mountains",
    "Sunset",
    "Desert",
    "Ocean",
    "Meadow",
    "Galaxy",
    "Snow",
    "Rain",
    "Waterfall",
    "Jungle",
    "Clouds",
    "fireworks",
    "sexy girl",
    "woman",
]
QUOTE_TXT = "1_quote.txt"
